name: xsflutter
description: JavaScript Flutter Framework,Using xsflutter lib, you can use JavaScript to develop flutter or use Dart to develop and compile to JS.
version: 0.2.5
homepage: https://github.com/xsflutter/xsflutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # XSFlutter Framework 必须的库
  vector_math: ^2.0.8
  expressions: ^0.1.2

  # https://github.com/tekartik/synchronized.dart
  synchronized: '>=1.5.1 <3.0.0'

  # https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  shared_preferences: '>=0.3.0 <3.0.0'
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    #xsflutter_js_framework
    - js_lib/

  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.xsyx.xsflutter
    pluginClass: XSFlutterPlugin




