name: xsflutter
description: JavaScript Flutter Framework,Using xsflutter lib, you can use JavaScript to develop flutter or use Dart to develop and compile to JS.
version: 0.2.5
homepage: https://github.com/xsflutter/xsflutter

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # XSFlutter Framework 必须的库
  vector_math: ^2.0.8
  expressions: ^0.1.5

  # https://github.com/tekartik/synchronized.dart
  synchronized: '>=2.2.0 <3.0.0'

  # https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  shared_preferences: '>=0.5.12+4 <2.0.0'

  # 包管理
  # https://github.com/flutter/plugins
  package_info: ^0.4.3

  #屏幕常亮
  wakelock: ^0.2.1+1 

  # 页面跳转
  # https://github.com/smrutiranjanrana/Flutter-URL-Launcher
  # 5.7.0
  url_launcher: ^5.7.0

  # 网络请求处理
  # https://github.com/flutterchina/dio
  dio: ^3.0.10  #latest version
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    #xsflutter_js_framework
    - js_lib/

  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.xsyx.xsflutter
    pluginClass: XSFlutterPlugin




