name: xsjsengine_example
description: Demonstrates how to use the xsjsengine plugin.
version: 0.2.5
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  xsflutter:
    path: ../XSFlutter/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    #copy js src ,xsjsflutter app demo 的js代码
    - js_src/
    - js_src/app_demo/
    - js_src/app_demo/component/
    - js_src/app_demo/examples/
    - js_src/app_demo/examples/animation/
    - js_src/app_demo/material/
    - js_src/app_demo/platform/
    - js_src/app_demo/profile/
    - js_src/app_demo/widget_examples/
    - js_src/app_demo/widget_examples/A/
    - js_src/app_demo/widget_examples/T/

    #mxflutter app demo 使用到的图片资源
    - packages/flutter_gallery_assets/people/ali_landscape.png
    - packages/flutter_gallery_assets/logos/flutter_white/logo.png
    - packages/flutter_gallery_assets/logos/fortnightly/fortnightly_logo.png
    - packages/flutter_gallery_assets/food/butternut_squash_soup.png
    - packages/flutter_gallery_assets/food/cherry_pie.png
    - packages/flutter_gallery_assets/food/chopped_beet_leaves.png
    - packages/flutter_gallery_assets/food/fruits.png
    - packages/flutter_gallery_assets/food/pesto_pasta.png
    - packages/flutter_gallery_assets/food/roasted_chicken.png
    - packages/flutter_gallery_assets/food/spanakopita.png
    - packages/flutter_gallery_assets/food/spinach_onion_salad.png
    - packages/flutter_gallery_assets/food/icons/fish.png
    - packages/flutter_gallery_assets/food/icons/healthy.png
    - packages/flutter_gallery_assets/food/icons/main.png
    - packages/flutter_gallery_assets/food/icons/meat.png
    - packages/flutter_gallery_assets/food/icons/quick.png
    - packages/flutter_gallery_assets/food/icons/spicy.png
    - packages/flutter_gallery_assets/food/icons/veggie.png
    - packages/flutter_gallery_assets/logos/pesto/logo_small.png
    - packages/flutter_gallery_assets/products/backpack.png
    - packages/flutter_gallery_assets/products/belt.png
    - packages/flutter_gallery_assets/products/cup.png
    - packages/flutter_gallery_assets/products/deskset.png
    - packages/flutter_gallery_assets/products/dress.png
    - packages/flutter_gallery_assets/products/earrings.png
    - packages/flutter_gallery_assets/products/flatwear.png
    - packages/flutter_gallery_assets/products/hat.png
    - packages/flutter_gallery_assets/products/jacket.png
    - packages/flutter_gallery_assets/products/jumper.png
    - packages/flutter_gallery_assets/products/kitchen_quattro.png
    - packages/flutter_gallery_assets/products/napkins.png
    - packages/flutter_gallery_assets/products/planters.png
    - packages/flutter_gallery_assets/products/platter.png
    - packages/flutter_gallery_assets/products/scarf.png
    - packages/flutter_gallery_assets/products/shirt.png
    - packages/flutter_gallery_assets/products/sunnies.png
    - packages/flutter_gallery_assets/products/sweater.png
    - packages/flutter_gallery_assets/products/sweats.png
    - packages/flutter_gallery_assets/products/table.png
    - packages/flutter_gallery_assets/products/teaset.png
    - packages/flutter_gallery_assets/products/top.png
    - packages/flutter_gallery_assets/people/square/ali.png
    - packages/flutter_gallery_assets/people/square/peter.png
    - packages/flutter_gallery_assets/people/square/sandra.png
    - packages/flutter_gallery_assets/people/square/stella.png
    - packages/flutter_gallery_assets/people/square/trevor.png

  fonts:
    - family: Raleway
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-Regular.ttf
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: packages/flutter_gallery_assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


