name: xsjsengine_example
description: Demonstrates how to use the xsjsengine plugin.
version: 1.0.5+5
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.10.2 <3.0.0"
  flutter: ">=1.22.2 <2.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  xsflutter:
    path: ../XSFlutter/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    #copy js src ,xsjsflutter app demo 的js代码
    - js_src/
    - js_src/demo/
    - js_src/demo/widgets/
    - js_src/demo/listview/
    - js_src/demo/base_widgets/
    - js_src/demo/packages/
    - js_src/demo/examples/
    - js_src/demo/dialog/
    - js_src/demo/utils/
    - js_src/demo/pull_to_refresh/
    - js_src/demo/easy_refresh/
    - js_src/demo/model/

    - assets/images/

    #mxflutter app demo 使用到的图片资源
    - packages/test.png
 
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


